name: Assets update

on:
  schedule:
    - cron:  '30 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Git
        uses: fregante/setup-git-user@v1
      - name: Run assets update
        run: | 
          git clone https://github.com/italia/design-scuole-pagine-statiche
          cd design-scuole-pagine-statiche && npm i && npm run build && cd ..
          cp ./design-scuole-pagine-statiche/dist/assets/css/scuole.css ./assets/css/scuole.css
          cp ./design-scuole-pagine-statiche/dist/assets/js/scuole.js ./assets/js/scuole.js
          rm -rf design-scuole-pagine-statiche
          git add assets/css/scuole.css assets/js/scuole.js
          git commit -m "chore(deps): update assets"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "chore(deps) update scuole.css"
          branch: feature/update-scuole-css